// AUTO-GENERATED by scripts/generate-asset-map.ts. Do not edit by hand.
/* eslint-disable @typescript-eslint/no-require-imports */
export const CORE_ASSET_MODULES: Record<string, number> = {
  'env_home_bg_bathroom_01': require('./assets/images/env_home_bg_bathroom_01.webp'),
  'env_home_bg_bedroom_01': require('./assets/images/env_home_bg_bedroom_01.webp'),
  'env_home_bg_kitchen_01': require('./assets/images/env_home_bg_kitchen_01.webp'),
  'env_home_bg_living_01': require('./assets/images/env_home_bg_living_01.webp'),
  'env_home_lamp_floor_off': require('./assets/images/env_home_lamp_floor_off.webp'),
  'env_home_lamp_floor_on': require('./assets/images/env_home_lamp_floor_on.webp'),
  'env_home_table_round': require('./assets/images/env_home_table_round.webp'),
  'env_home_toybox_closed': require('./assets/images/env_home_toybox_closed.webp'),
  'env_home_toybox_open': require('./assets/images/env_home_toybox_open.webp'),
  'obj_food_apple_red': require('./assets/images/obj_food_apple_red.webp'),
  'obj_toy_ball': require('./assets/images/obj_toy_ball.webp'),
};
