// AUTO-GENERATED by scripts/generate-asset-map.ts. Do not edit by hand.
/* eslint-disable @typescript-eslint/no-require-imports */
import type { RawPack } from '../src/engine/content/raw-pack';

import { CORE_ASSET_MODULES } from './core/assets.generated';

/** Packs bundled in the binary (CONTENT_SYSTEM §2). */
export const BUNDLED_PACKS: RawPack[] = [
  {
    manifest: { file: 'manifest.json', data: require('./core/manifest.json') },
    assets: { file: 'assets.json', data: require('./core/assets.json') },
    prefabs: [
      { file: 'prefabs/clothing/boots_brown.json', data: require('./core/prefabs/clothing/boots_brown.json') },
      { file: 'prefabs/clothing/hoodie_purple.json', data: require('./core/prefabs/clothing/hoodie_purple.json') },
      { file: 'prefabs/clothing/jeans_blue.json', data: require('./core/prefabs/clothing/jeans_blue.json') },
      { file: 'prefabs/clothing/leggings_yellow.json', data: require('./core/prefabs/clothing/leggings_yellow.json') },
      { file: 'prefabs/clothing/pants_green.json', data: require('./core/prefabs/clothing/pants_green.json') },
      { file: 'prefabs/clothing/sandals_blue.json', data: require('./core/prefabs/clothing/sandals_blue.json') },
      { file: 'prefabs/clothing/shirt_dino_orange.json', data: require('./core/prefabs/clothing/shirt_dino_orange.json') },
      { file: 'prefabs/clothing/shirt_heart_pink.json', data: require('./core/prefabs/clothing/shirt_heart_pink.json') },
      { file: 'prefabs/clothing/shirt_plain_green.json', data: require('./core/prefabs/clothing/shirt_plain_green.json') },
      { file: 'prefabs/clothing/shirt_star_yellow.json', data: require('./core/prefabs/clothing/shirt_star_yellow.json') },
      { file: 'prefabs/clothing/shirt_stripe_blue.json', data: require('./core/prefabs/clothing/shirt_stripe_blue.json') },
      { file: 'prefabs/clothing/shoes_black.json', data: require('./core/prefabs/clothing/shoes_black.json') },
      { file: 'prefabs/clothing/shorts_red.json', data: require('./core/prefabs/clothing/shorts_red.json') },
      { file: 'prefabs/clothing/skirt_pink.json', data: require('./core/prefabs/clothing/skirt_pink.json') },
      { file: 'prefabs/clothing/sneakers_red.json', data: require('./core/prefabs/clothing/sneakers_red.json') },
      { file: 'prefabs/decor/lamp_floor.json', data: require('./core/prefabs/decor/lamp_floor.json') },
      { file: 'prefabs/food/apple_red.json', data: require('./core/prefabs/food/apple_red.json') },
      { file: 'prefabs/furniture/table_round.json', data: require('./core/prefabs/furniture/table_round.json') },
      { file: 'prefabs/furniture/toybox.json', data: require('./core/prefabs/furniture/toybox.json') },
      { file: 'prefabs/toy/ball.json', data: require('./core/prefabs/toy/ball.json') },
    ],
    scenes: [
      { file: 'scenes/home.json', data: require('./core/scenes/home.json') },
    ],
    rules: [
      { file: 'interactions/core.rules.json', data: require('./core/interactions/core.rules.json') },
    ],
    characters: { file: 'characters/parts.json', data: require('./core/characters/parts.json') },
    locales: { en: { file: 'locales/en.json', data: require('./core/locales/en.json') }, es: { file: 'locales/es.json', data: require('./core/locales/es.json') } },
  },
];

/** AssetKey → Metro module id, for every bundled pack. */
export const BUNDLED_ASSET_MODULES: Record<string, number> = {
  ...CORE_ASSET_MODULES,
};
