/**
 * Generates static `require` maps for Metro (HU-GAME-068 R6, CONTENT_SYSTEM §2):
 *   - content/<pack>/assets.generated.ts: one require per image/audio key of assets.json
 *   - content/index.ts: bundled packs with their JSON files, plus the merged asset module map
 * Output is deterministic (sorted). `--check` writes nothing and fails if the files are stale.
 *
 * Usage: npm run content:assets [-- --check]
 */
import fs from 'fs';
import path from 'path';

import { listPackDirs, readPackDir } from './lib/pack-fs';

const ROOT = path.resolve(__dirname, '..');
const CONTENT = path.join(ROOT, 'content');
const HEADER = '// AUTO-GENERATED by scripts/generate-asset-map.ts. Do not edit by hand.\n';

interface Generated {
  file: string;
  content: string;
}

const ident = (packId: string) => `${packId.toUpperCase()}_ASSET_MODULES`;
const q = (s: string) => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

export function generate(contentDir = CONTENT): { files: Generated[]; errors: string[] } {
  const errors: string[] = [];
  const files: Generated[] = [];
  const packs = listPackDirs(contentDir).map((dir) => ({ dir, id: path.basename(dir), raw: readPackDir(dir) }));
  for (const pack of packs) {
    const assets = (pack.raw.assets?.data ?? { images: {}, audio: {} }) as {
      images?: Record<string, { file: string }>;
      audio?: Record<string, { file: string }>;
    };
    const entries = [...Object.entries(assets.images ?? {}), ...Object.entries(assets.audio ?? {})].sort(([a], [b]) =>
      a.localeCompare(b),
    );
    const lines: string[] = [];
    for (const [key, { file }] of entries) {
      if (!fs.existsSync(path.join(pack.dir, file))) {
        errors.push(`[${pack.id}] asset "${key}": file "${file}" does not exist`);
        continue;
      }
      lines.push(`  ${q(key)}: require(${q('./' + file)}),`);
    }
    files.push({
      file: path.join(pack.dir, 'assets.generated.ts'),
      content: `${HEADER}/* eslint-disable @typescript-eslint/no-require-imports */\nexport const ${ident(pack.id)}: Record<string, number> = {\n${lines.join('\n')}\n};\n`,
    });
  }

  const req = (packId: string, file: string) => `require(${q(`./${packId}/${file}`)})`;
  const rawFile = (packId: string, file: string) => `{ file: ${q(file)}, data: ${req(packId, file)} }`;
  const packBlocks = packs.map(({ id, raw }) => {
    const list = (items: { file: string }[]) => `[${items.map((f) => `\n      ${rawFile(id, f.file)},`).join('')}\n    ]`;
    const locales = Object.entries(raw.locales)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([loc, f]) => `${loc}: ${rawFile(id, f!.file)}`)
      .join(', ');
    return `  {
    manifest: ${rawFile(id, raw.manifest.file)},
    assets: ${raw.assets ? rawFile(id, raw.assets.file) : 'undefined'},
    prefabs: ${list(raw.prefabs)},
    scenes: ${list(raw.scenes)},
    rules: ${list(raw.rules)},
    locales: { ${locales} },
  },`;
  });
  const imports = packs.map(({ id }) => `import { ${ident(id)} } from './${id}/assets.generated';`).join('\n');
  files.push({
    file: path.join(contentDir, 'index.ts'),
    content: `${HEADER}/* eslint-disable @typescript-eslint/no-require-imports */
import type { RawPack } from '../src/engine/content/raw-pack';

${imports}

/** Packs bundled in the binary (CONTENT_SYSTEM §2). */
export const BUNDLED_PACKS: RawPack[] = [
${packBlocks.join('\n')}
];

/** AssetKey → Metro module id, for every bundled pack. */
export const BUNDLED_ASSET_MODULES: Record<string, number> = {
${packs.map(({ id }) => `  ...${ident(id)},`).join('\n')}
};
`,
  });
  return { files, errors };
}

function main(argv: string[]): number {
  const check = argv.includes('--check');
  const unknown = argv.filter((a) => a !== '--check');
  if (unknown.length) {
    console.error(`Unknown option(s): ${unknown.join(' ')}\nUsage: generate-asset-map [--check]`);
    return 2;
  }
  let result;
  try {
    result = generate();
  } catch (e) {
    console.error((e as Error).message);
    return 1;
  }
  if (result.errors.length) {
    for (const e of result.errors) console.error(e);
    return 1;
  }
  const stale = result.files.filter((f) => !fs.existsSync(f.file) || fs.readFileSync(f.file, 'utf8') !== f.content);
  if (check) {
    if (stale.length) {
      for (const f of stale) console.error(`Stale generated file: ${path.relative(ROOT, f.file)}`);
      console.error('Run "npm run content:assets" and commit the result.');
      return 1;
    }
    console.log('Generated content maps are up to date.');
    return 0;
  }
  for (const f of stale) fs.writeFileSync(f.file, f.content);
  console.log(`Generated ${result.files.length} file(s), ${stale.length} changed.`);
  return 0;
}

if (require.main === module) process.exit(main(process.argv.slice(2)));
